#!/usr/bin/env bash
#
# Install (or remove) the Stream Playing daemon and Plasma applet for the
# current user. Nothing is written outside $HOME.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/streamplay"
BIN_DIR="$HOME/.local/bin"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
APPLET_ID="org.kde.plasma.streamplay"

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m==>\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m==>\033[0m %s\n' "$*" >&2; exit 1; }

check_requirements() {
    local missing=()
    command -v python3 >/dev/null || missing+=("python3")
    command -v mpv     >/dev/null || missing+=("mpv")
    command -v kpackagetool6 >/dev/null || missing+=("kpackagetool6 (plasma-workspace)")
    python3 -c "import requests"  2>/dev/null || missing+=("python-requests")
    python3 -c "import websockets" 2>/dev/null || missing+=("python-websockets")

    if [ ${#missing[@]} -gt 0 ]; then
        die "Missing requirements: ${missing[*]}"
    fi

    # MPRIS is optional: without it everything works except the KDE media
    # controls, so this is a warning rather than a hard failure.
    python3 -c "import dbus, gi" 2>/dev/null \
        || warn "python-dbus and python-gobject are missing; Now Playing / media keys will not work."
}

install_daemon() {
    say "Installing the daemon into $DATA_DIR"
    mkdir -p "$DATA_DIR" "$BIN_DIR"
    rm -rf "${DATA_DIR:?}/streamplay"
    cp -r "$HERE/daemon/streamplay" "$DATA_DIR/streamplay"
    find "$DATA_DIR/streamplay" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true

    cat > "$BIN_DIR/streamplayd" <<EOF
#!/usr/bin/env bash
# Generated by install.sh
export PYTHONPATH="$DATA_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m streamplay "\$@"
EOF
    chmod +x "$BIN_DIR/streamplayd"

    case ":$PATH:" in
        *":$BIN_DIR:"*) ;;
        *) warn "$BIN_DIR is not on your PATH; the systemd unit uses the full path anyway." ;;
    esac
}

install_service() {
    say "Installing the systemd user service"
    mkdir -p "$UNIT_DIR"
    cp "$HERE/systemd/streamplay.service" "$UNIT_DIR/streamplay.service"
    systemctl --user daemon-reload
    systemctl --user enable --now streamplay.service
    sleep 1
    if systemctl --user is-active --quiet streamplay.service; then
        say "The service is running."
    else
        warn "The service did not start. Check: journalctl --user -u streamplay -n 40"
    fi
}

install_applet() {
    say "Installing the Plasma applet"
    if kpackagetool6 --type Plasma/Applet --list 2>/dev/null | grep -qx "$APPLET_ID"; then
        kpackagetool6 --type Plasma/Applet --upgrade "$HERE/plasmoid/package"
    else
        kpackagetool6 --type Plasma/Applet --install "$HERE/plasmoid/package"
    fi
}

uninstall() {
    say "Removing the systemd user service"
    systemctl --user disable --now streamplay.service 2>/dev/null || true
    rm -f "$UNIT_DIR/streamplay.service"
    systemctl --user daemon-reload 2>/dev/null || true

    say "Removing the applet"
    kpackagetool6 --type Plasma/Applet --remove "$APPLET_ID" 2>/dev/null || true

    say "Removing the daemon"
    rm -rf "$DATA_DIR"
    rm -f "$BIN_DIR/streamplayd"

    say "Your servers and settings are untouched in ${XDG_CONFIG_HOME:-$HOME/.config}/streamplay."
}

case "${1:-install}" in
    install)
        check_requirements
        install_daemon
        install_service
        install_applet
        echo
        say "Done. Add the “Stream Playing” widget to a panel or the desktop,"
        say "then use its settings to add your Navidrome/Subsonic or Kodi servers."
        ;;
    uninstall|remove)
        uninstall
        ;;
    *)
        die "Usage: $0 [install|uninstall]"
        ;;
esac
