panels().forEach(p => p.remove());
const panel = new Panel;
panel.location = "bottom";
panel.height = 44;
panel.addWidget("org.kde.plasma.kickoff");
const tasks = panel.addWidget("org.kde.plasma.icontasks");
tasks.currentConfigGroup = ["General"];
tasks.writeConfig("launchers", ["applications:org.kde.dolphin.desktop", "applications:org.kde.konsole.desktop", "applications:org.kde.kate.desktop", "applications:org.kde.okular.desktop"]);
panel.addWidget("org.kde.plasma.marginsseparator");
panel.addWidget("io.github.leissa.streamplay");
panel.addWidget("org.kde.plasma.systemtray");
panel.addWidget("org.kde.plasma.digitalclock");
